### PR TITLE
merged upstream sparkle-project

### PR DESCRIPTION
**Pull request by pixeled**
merged current `sparkle-project/Sparkle` into this branch.
built framework.
dropped into `ut_web/deps/sparkle` to test (Xcode could see new headers, new methods etc.)
things working well.

"build All" works just fine. my thought was to just merge, let deps be built, then build test branches of `ut_web`

as far as I see, the updated sparkle is backwards compatible.. but we should not be in limbo too long

### CODE REVIEW

**Comment by ssiloti** [comment]
This should be done as a proper git merge (with history) instead of a single massive commit.

**Comment by pixeled** [comment]
I'm not quite following..
I did a `git merge upstream sparkle-project/Sparkle`
or something very similar.

whenever I've merged branches in the past, you still have to commit..
since there were literally 1066 commits we missed, yes.. the diff is going to be big.

if you could recommend a better process than 

`git merge {upstream`
`git commit`

I'd be happy do do it however you'd like.

**Comment by pixeled** [comment]
I'm going to try a `git rebase {master}` to see if that keeps the history for you.

**Comment by ssiloti** [comment]
Hrm, I don't know how you managed to do it but you made git produce a squashed merge. What happens when you add the `--no-squash` option to your merge command?

**Pull request closed without merging**
